### ISSUE TITLE
Endpoints as parameters

### ISSUE THREAD

**Issue by matiasdecarli** [chef/chef-provisioning-azure#1]
I know this is a very early release, but I think it will be a great feature to have an array of local and public TCP ports to be opened, as a parameters

**Comment by stuartpreston** [comment]
Just to confirm I have tested and this scenario is working with the latest release v0.2.  You need to add a tcp_endpoints parameter to the machine_options hashmap, e.g.

```ruby
require 'chef/provisioning/azure_driver'
with_driver 'azure'

machine_options = {
    :bootstrap_options => {
      :cloud_service_name => 'pendricacloud01',
      :storage_account_name => 'pendricastore01',
      :vm_size => "Small",
      :location => 'North Europe',
      :tcp_endpoints => "8080:80,8443:443"
    },
    # Until SSH keys are supported (soon)
    :password => "P2ssw0rd",
    :image_id => 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_1-LTS-amd64-server-20140927-en-us-30GB'
}

machine 'pendev01app01' do
  machine_options machine_options
end
```

In addition to the ports opened by default, you will see the endpoint mappings created correctly in Azure management ui:

![spvm2015_cloudapp_net 4](https://cloud.githubusercontent.com/assets/6384654/6252293/21c3b8ce-b791-11e4-92e4-ae27e497bf81.png)
