### ISSUE TITLE
Timeline for Currently untested/Known issues

### ISSUE THREAD

**Issue by tmaier** [chef/chef-provisioning-azure#13]
https://github.com/chef/chef-provisioning-azure#currently-untestedknown-issues	

We consider to use Chef Enterprise and chef-provisioning on a big project on Azure.

Do you have any timeline for the currently untested and known issues?

* [ ]	Windows/WinRM bootstrap
* [ ]	Load-balanced sets
* [ ]	Availability sets/Fault domains
* [ ]	Cloud Service autoscaling
* [ ]	Endpoint monitoring
* [ ]	Additional disk volumes
* [ ]	Affinity groups
* [ ]	Direct server return IP addresses
* [ ]	Reserved/Static IP addresses
* [ ]	Virtual network allocation
* [ ]	Bootstrap via internal (private) addresses
* [ ]	CDN/TrafficManager
* [ ]	Non-IaaS Azure services (e.g CDN/TrafficManager Service Bus, Azure SQL Database, Media Services, Redis Cache)

**Comment by stuartpreston** [comment]
I believe I'm correct (someone from Chef can chime in?) in saying there is no specific timeline/milestone plan for the Azure driver - I have been submitting pull requests over the last month to get it to a working, stabilised state and will continue to do so in my spare time after customer work.

Windows/WinRM support should be there next, then I'll be looking at some of the other items on the list, some will be small changes others will require.

If you can suggest which features you think you will need in order, that may help me/other contributors prioritise the work.

**Comment by stuartpreston** [comment]
Windows/WinRM support is there as of Chef-Provisioning 1.0.
I'm closing this issue for now, please keep an eye on the readme for updates when new features get released.
