### ISSUE TITLE
Guest agent is not provisioned

### ISSUE THREAD

**Issue by adamedx** [chef/chef-provisioning-azure#26]
In the role xml, the ProvisionGuestAgent element should be set to false by default. This is what the Azure portal does when a new VM is created. Without it, VM extensions cannot be added later after the VM is created.

**Comment by stuartpreston** [comment]
@adamedx Agreed we should fix this.  Slightly surprised that the lack of the element on creation prevents it being added later.  Would need to slot in a fix to the Azure SDK for this, roughly [here](https://github.com/stuartpreston/azure-sdk-for-ruby/blob/master/lib/azure/virtual_machine_management/serialization.rb#L86) and [here](https://github.com/stuartpreston/azure-sdk-for-ruby/blob/master/lib/azure/virtual_machine_management/serialization.rb#L271).  Do you need this for something urgently?

**Comment by adamedx** [comment]
@stuartpreston this is certainly not urgent, at the moment I just wanted to make sure this was tracked. Eventually, it will be great if we can do the actual configuration using the Azure Chef extension rather than winrm,  similar to `knife-azure`s [--cloud-api bootstrap protocol option](https://github.com/chef/knife-azure/blob/1.4.0/DOC_CHANGES.md#cloud-api-value-for-bootstrap_protocol_option-in-server-create).

Thank you for looking at this.

**Comment by stuartpreston** [comment]
I'm closing this as the ARM driver being built has been shown to work with the Chef VM Extensions, and we will not provide a fix for ASM any more as the resources are now legacy.
