### ISSUE TITLE
Specification of storage account should be optional

### ISSUE THREAD

**Issue by adamedx** [chef/chef-provisioning-azure#27]
Azure subscriptions can have a default storage account, obviating the need to specify the storage account in provisioning's Azure driver config. When I created an Azure VM with provisioning, it would not let me proceed without specifying the storage account, even though I had a default configured.

As an example, see the behavior of the `knife-azure` plug-in, which looks for a storage account in the VM's geography and uses the first one it finds:
https://github.com/chef/knife-azure/blob/1.4.0/lib/chef/knife/azure_server_create.rb#L498

`chef-provisioning-azure` should adopt similar behavior if possible.

See this url for the source of the PowerShell example below that sets the storage account:
http://michaelwasham.com/2012/03/12/windows-azure-powershell-cmdlets-2-2-2-release/

```powershell
   # Specify the default storage account to use for the subscription
     Set-Subscription -SubscriptionName org-sub1 -DefaultStorageAccount mystoragename1
```

**Comment by stuartpreston** [comment]
@adamedx The examples in the [readme.md](https://github.com/chef/chef-provisioning-azure#windows) are up to date and do list the storage account as a required option.

Right now I am hesitant to work around the functionality provided by the Azure (ServiceManagement) SDK especially in the context of future compatibility (AzureResourceManager), where creating a Storage Account will **require** specifying a ResourceGroup first.  But will put it on the backlog to investigate for the ServiceManagement version.

**Comment by adamedx** [comment]
Yup, I think if you're looking forward to going off of Resource Manager, then it's fine to defer resolving this until then. Thanks!

**Comment by stuartpreston** [comment]
Closing this as won't fix the ASM driver.  The ARM driver will require the specification of a storage account for compute resource as this must exist in a Resource Group.
