### ISSUE TITLE
Localadmin user name for Windows systems is not configurable

### ISSUE THREAD

**Issue by adamedx** [chef/chef-provisioning-azure#28]
In the azure driver config, it seems to be mandatory to specify 'localadmin' as the user name and still have winrm bootstrap work. This username should be configurable, just as the password is. In the `knife-azure` gem, the username is configurable: https://github.com/chef/knife-azure/blob/1.4.0/lib/azure/role.rb#L278

**Comment by stuartpreston** [comment]
@adamedx Looks like a couple of things need fixing here... we select the default_ssh_username if no ```:bootstrap_options[:vm_user]``` is set https://github.com/chef/chef-provisioning-azure/blob/master/lib/chef/provisioning/azure_driver/driver.rb#L106 - this would create a machine using the username 'ubuntu' and then attempt to winrm bootstrap it using 'localadmin'

So the workaround is to always set ```:bootstrap_options[:vm_user]``` for Windows VM roles until fixed.

**Comment by adamedx** [comment]
I'll give that workaround a try @stuartpreston -- thank you!

**Comment by stuartpreston** [comment]
Closing this as no further code changes are planned before the ARM driver.
