### ISSUE TITLE
vm name cannot have dots in it

### ISSUE THREAD

**Issue by irvingpop** [chef/chef-provisioning-azure#32]
Creating a `machine 'standalone1.trusty.azure'` will result in:

```
BadRequest : Parameter value 'standalone1.trusty.azure' specified for parameter 'RoleName' is invalid.
```

**Comment by irvingpop** [comment]
there are also surprises with the storage account name.

**Comment by stuartpreston** [comment]
Perhaps we could write in some validation that is as vague as the error message shown in the Azure portal for VM names ;)

![create_vm_-_microsoft_azure](https://cloud.githubusercontent.com/assets/6384654/8144526/d696b492-11da-11e5-8772-9bfd0cf3fbfa.png)

**Comment by stuartpreston** [comment]
I'm closing this as we will not fix in the current driver. The new ARM driver I am building does have some rules that check server names and storage account names are valid.
