### ISSUE TITLE
machine resource :converge_only implementation?

### ISSUE THREAD

**Issue by anthonyvdis** [chef/chef-provisioning-azure#43]
It looks like the :converge_only action isn't implemented because the connect_to_machine method isn't implemented in the driver. I would like to have this action because I am calling the machine resource multiple times on the same VM, and each run appears to re-download and re-run the chef-client omnibus installer, which is adding unnecessary time to my provisioning process.

Attempting the action gives this error:

    Chef::Provisioning::AzureDriver::Driver does not implement connect_to_machine

I see this issue: https://github.com/chef/chef-provisioning-azure/issues/21 but I'm not sure how related it is.

Can anyone advise on implementing connect_to_machine? Is it planned? Possible? Can we instead simply prevent the default action from reinstalling the chef-client if it's already there?

Thanks

**Comment by stuartpreston** [comment]
I personally haven't spent any time on this. The problem with connect_to_machine is that it relies on a direct WinRM connection from your provisioning node/client, and in Azure this is not guaranteed and/or likely to be on a different set of ports per VM.

For V2/Azure Resource Manager mode machines, it is even less likely that you would have direct connectivity to the WinRM ports on each VM, hence the preference there is to use Chef Provisioning (see http://github.com/pendrica/chef-provisioning-azurerm) as a means to get a VM or other resources created and up and running with a Chef VM Extension, which then is a bit more self managing.

I'm going to close this for now but please reopen or @ me if you want to discuss further.
