### ISSUE TITLE
Can only provision and bootstrap the first VM in any given cloud service

### ISSUE THREAD

**Issue by stuartpreston** [chef/chef-provisioning-azure#6]
As at release 0.2, it is not possible to create more than a single VM using chef-provisioning-azure. The issues can be summarised as:

* Adding a second VM to a cloud service fails with the message: "ConflictError : The specified deployment slot Production is occupied." 
* SSH bootstrap transport always uses the listening SSH port of the machine irrespective of the public endpoint port in use and hence overwrites the /etc/chef/client.rb of the first VM added to the cloud service

I have made some fixes in my fork to address these problems and will be sending in the PR shortly, just recording this issue first.

**Comment by jkeiser** [comment]
This was fixed by the associated merge :)  Thanks!

**Comment by aarsan** [comment]
I am currently getting "ConflictError : The specified deployment slot Production is occupied." and only able to create a single VM in a cloud service with the latest version. This is for Windows.
